### ISSUE TITLE
Question: Defining a struct where one of its fields is a bitfield

### ISSUE THREAD

**Issue by tandasat** [wbenny/ia32-doc#6]
How one can define and generate a struct where one of its fields needs to be a bitfield? Take  `VMCS` as an example, the `RevisionId` is defined as a pure integer while it should have been defined as two two bit fields, that is,
```cpp
typedef struct
{
  UINT32 RevisionId;
/*
It should have been like this:
  UINT32 RevisionId : 31;
  UINT32 ShadowVmcsIndicator : 1;
*/
  UINT32 AbortIndicator;
  UINT8 Data[4088];
} VMCS;
```
Can you tell me one can define a structure like this, or even better, can you update the yaml file so I can learn from a sample :)?

**Comment by wbenny** [comment]
Currently, you can't. The best you can do now is to make nested bitfield inside of a struct, like this:
```yaml
- name: VMCS
  type: struct
  fields:
    - name: DUMMY
      type: bitfield
      size: 32
      fields:
        - bit: 0-30
          name: REVISION_ID

        - bit: 31
          name: SHADOW_VMCS_INDICATOR

    - size: 32
      name: ABORT_INDICATOR

    - size: 32704  # 4088
      name: DATA

```

What do you think about nested unnamed bitfield structs? Say,
```c
typedef struct
{
  struct
  {
    UINT32 RevisionId : 31;
    UINT32 ShadowVmcsIndicator : 1;
  };
  UINT32 AbortIndicator;
  UINT8 Data[4088];
} VMCS;
```

If that suffices, I will implement a mechanism that supports it.
